listen-address=10.1.1.1
no-hosts
log-queries
log-facility=/var/log/dnsmasq.log
dhcp-range=10.1.1.2,10.1.1.254,72h
dhcp-option=option:router,10.1.1.1
dhcp-authoritative
dhcp-option=114,http://start.ravendb/
dhcp-option=160,http://start.ravendb/

# Resolve everything to the portal's IP address.
address=/#/10.1.1.1


# Android Internet Conectivity Test Domains
address=/clients1.google.com/10.1.1.1
address=/clients3.google.com/10.1.1.1
address=/connectivitycheck.android.com/10.1.1.1
address=/connectivitycheck.gstatic.com/10.1.1.1

# Apple captive detection domains
address=/captive.apple.com/10.1.1.1
address=/www.apple.com/10.1.1.1

# Microsoft captive detection domains
address=/msftconnecttest.com/10.1.1.1
address=/www.msftconnecttest.com/10.1.1.1
address=/msftncsi.com/10.1.1.1
address=/www.msftncsi.com/10.1.1.1
address=/dns.msftncsi.com/10.1.1.1