const cards = [
  {
    name: "Raspberry Pi",
    description:
      "Raspberry Pi Stack Exchange is a question and answer site for users and developers of hardware and software for Raspberry Pi",
    image: "raspberrypi.svg",
    alt: "Raspberry Pi logo",
  },
  {
    name: "Server Fault",
    description:
      "Server Faults is a question and answer site for system and network administrators",
    image: "serverfault.svg",
  },
  {
    name: "Unix & Linux",
    description:
      "Unix & Linux Stack Exchange Is a question and answer site for users of Linux, FreeBSD and other Un*x-like operating systems",
    image: "unix.svg",
  },
];

export function getCards() {
  return cards;
}

const demoQuestions = [
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-12-01T21:55:15.6200000",
    Score: 0,
    ViewCount: 10,
    Body: "<p>Need to stream a feed from a flir lepton to a small version raspberry pi  to a .24 inch ferroelectric liquid crystal micro display. I have SOME experience with raspberry pi, reading questions and answers on here about programing raspberry is how i gained my limited experience. That being considered im just gonna ask from the get go before i buy the hardware how those who are experienced in such things accomplish this, what hardware they would use, and what firmware or whatever it would be they would utilize to do this. This is also the first question ive ever posted to any forum im the walking stereotype of a man not asking directions or looking at instructions.</p>\n",
    Owner: "users/158164",
    LastEditor: null,
    LastEditDate: null,
    Title:
      "Need to stream a feed from a flir lepton to a small version raspberry pi to a .24 inch ferroelectric liquid crystal micro display",
    Tags: ["hardware", "camera", "display", "raspicam", "video-input"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180335-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/145164",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1763337Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "serverfault",
    CreationDate: "2023-12-01T11:46:25.1800000",
    Score: 0,
    ViewCount: 13,
    Body: '<p>I\'m using raspberry pi 4 with <a href="https://www.arducam.com/product/arducam-16mp-imx519-autofocus-synchronized-quad-camera-kit-for-raspberry-pi-nvidia-jetson-nano-xavier-nx/" rel="nofollow noreferrer">Arducam quad camera kit</a> and <a href="https://www.reichelt.de/de/de/raspberry-pi-kamera-5mp-160--rpi-wwcam-p148944.html?trstct=pos_1&amp;nbc=1&amp;&amp;r=1" rel="nofollow noreferrer">HD-Weitwinkel cameras</a>. The cameras are not found when I reboot raspberrypi. However, when I reinstall raspberrypi os bullseye legacy, the cameras are recongized and it works as expected.</p>\n<pre><code>user@raspberrypi:~ $ libcamera-hello \nMade X/EGL preview window\n[1:34:32.981645903] [1978]  INFO Camera camera_manager.cpp:297 libcamera v0.0.0+4367-ad9428b4\nERROR: *** no cameras available ***\n</code></pre>\n<p>The os specifications are below:</p>\n<pre><code>user@raspberrypi:~ $ cat /etc/os-release\nPRETTY_NAME=&quot;Raspbian GNU/Linux 11 (bullseye)&quot;\nNAME=&quot;Raspbian GNU/Linux&quot;\nVERSION_ID=&quot;11&quot;\nVERSION=&quot;11 (bullseye)&quot;\nVERSION_CODENAME=bullseye\nID=raspbian\nID_LIKE=debian\nHOME_URL=&quot;http://www.raspbian.org/&quot;\nSUPPORT_URL=&quot;http://www.raspbian.org/RaspbianForums&quot;\nBUG_REPORT_URL=&quot;http://www.raspbian.org/RaspbianBugs&quot;\n\n\nuser@raspberrypi:~ $ uname -m\naarch64\n</code></pre>\n<p>The config file:</p>\n<pre><code># For more options and information see\n# http://rpf.io/configtxt\n# Some settings may impact device functionality. See link above for details\n\n# uncomment if you get no picture on HDMI for a default &quot;safe&quot; mode\n#hdmi_safe=1\n\n# uncomment the following to adjust overscan. Use positive numbers if console\n# goes off screen, and negative if there is too much border\n#overscan_left=16\n#overscan_right=16\n#overscan_top=16\n#overscan_bottom=16\n\n# uncomment to force a console size. By default it will be display\'s size minus\n# overscan.\n#framebuffer_width=1280\n#framebuffer_height=720\n\n# uncomment if hdmi display is not detected and composite is being output\n#hdmi_force_hotplug=1\n\n# uncomment to force a specific HDMI mode (this will force VGA)\n#hdmi_group=1\n#hdmi_mode=1\n\n# uncomment to force a HDMI mode rather than DVI. This can make audio work in\n# DMT (computer monitor) modes\n#hdmi_drive=2\n\n# uncomment to increase signal to HDMI, if you have interference, blanking, or\n# no display\n#config_hdmi_boost=4\n\n# uncomment for composite PAL\n#sdtv_mode=2\n\n#uncomment to overclock the arm. 700 MHz is the default.\n#arm_freq=800\n\n# Uncomment some or all of these to enable the optional hardware interfaces\ndtparam=i2c_arm=on\n#dtparam=i2s=on\n#dtparam=spi=on\n\n# Uncomment this to enable infrared communication.\n#dtoverlay=gpio-ir,gpio_pin=17\n#dtoverlay=gpio-ir-tx,gpio_pin=18\n\n# Additional overlays and parameters are documented /boot/overlays/README\n\n# Enable audio (loads snd_bcm2835)\ndtparam=audio=on\n\n# Automatically load overlays for detected cameras\ncamera_auto_detect=0\n\n# Automatically load overlays for detected DSI displays\ndisplay_auto_detect=1\n\n# Enable DRM VC4 V3D driver\ndtoverlay=vc4-kms-v3d\nmax_framebuffers=2\n\n# Disable compensation for displays with overscan\ndisable_overscan=1\n\n[cm4]\n# Enable host mode on the 2711 built-in XHCI USB controller.\n# This line should be removed if the legacy DWC2 controller is required\n# (e.g. for USB device mode) or if USB support is not required.\notg_mode=1\n\n[all]\n\n[pi4]\n# Run as fast as firmware / board allows\narm_boost=1\n\n[all]\ndtparam=i2_vc=on\ndtparam=i2c10=on\ndtoverlay=ov5647\ndtoverlay=arducam-pivariety\n</code></pre>\n<p>I have reinstalled raspberry os bullseye legacy twice to confirm the issue. It recongnizes the cameras and works as expected, but when it\'s rebooted, non of the cameras are found.</p>\n<p>Any suggestes regarding solving the issue is appreciated.</p>\n',
    Owner: "users/158153",
    LastEditor: null,
    LastEditDate: null,
    Title: "cameras not found after rebooting",
    Tags: ["pi-4", "camera", "libcamera"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180331-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/145159",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1759446Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "unix",
    CreationDate: "2023-11-30T08:56:35.3900000",
    Score: 0,
    ViewCount: 22,
    Body: "<p>I have a strange issue with my camera. I have installed it correctly, if I enter:</p>\n<pre><code>libcamera-still -o test.jpg\n[0:47:15.362288136] [3186]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f\n[0:47:15.417510467] [3187]  INFO RPI vc4.cpp:437 Registered camera /base/soc/i2c0mux/i2c@1/imx296@1a to Unicam device /dev/media1 and ISP device /dev/media2\n[0:47:15.417688132] [3187]  INFO RPI pipeline_base.cpp:1101 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'\n[0:47:15.422014078] [3186]  INFO Camera camera.cpp:1033 configuring streams: (0) 728x544-YUV420\n[0:47:15.422787605] [3187]  INFO RPI vc4.cpp:565 Sensor: /base/soc/i2c0mux/i2c@1/imx296@1a - Selected sensor format: 1456x1088-SBGGR10_1X10 - Selected unicam format: 1456x1088-pBAA\n[0:47:21.040437623] [3186]  INFO Camera camera.cpp:1033 configuring streams: (0) 1456x1088-YUV420 (1) 1456x1088-SBGGR10_CSI2P\n[0:47:21.041348501] [3187]  INFO RPI vc4.cpp:565 Sensor: /base/soc/i2c0mux/i2c@1/imx296@1a - Selected sensor format: 1456x1088-SBGGR10_1X10 - Selected unicam format: 1456x1088-pBAA\nStill capture image received\n</code></pre>\n<p>I'm getting a blur preview, but I can see something.\n<a href=\"https://i.stack.imgur.com/TwOl8.jpg\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/TwOl8.jpg\" alt=\"enter image description here\" /></a></p>\n<p>The camera has been switch on on the raspi config menu.</p>\n<p><strong>BUT</strong>, I can't see it in the Raspberry Pi Configuration window (with interfaces, above SSH). BTW, all interfaces are ON.</p>\n<p>If I enter:</p>\n<pre><code>vcgencmd get_camera\n</code></pre>\n<p>I get:</p>\n<pre><code>supported=0 detected=0, libcamera interfaces=0\n</code></pre>\n<pre><code>raspistill -o image.jpg\nmmal: Cannot read camera info, keeping the defaults for OV5647\nmmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)\nmmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)\nmmal: Failed to create camera component\nmmal: main: Failed to create camera component\nmmal: Camera is not enabled in this build. Try running &quot;sudo raspi-config&quot; and ensure that &quot;camera&quot; has been enabled\n</code></pre>\n<p>I run:</p>\n<pre><code>sudo apt-get upgrade\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n</code></pre>\n<p>Please, help me Obi-Wan, you are my only hope :D</p>\n",
    Owner: "users/158129",
    LastEditor: "users/94397",
    LastEditDate: "2023-11-30T16:29:31.4230000",
    Title: "Issue with 12-megapixel High Quality Camera",
    Tags: ["camera"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180323-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/145150",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1750159Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-11-27T11:17:37.1470000",
    Score: -1,
    ViewCount: 9,
    Body: "<p>How to fetch images from camera with DMA?</p>\n<p>I have a imxXXX-like camera which seems to work only with DMA. Not an expert, but, from what I understand, DMA is like MMAP but with different kind of buffers (allowing async operations).</p>\n<p>Can somebody detail the steps to follow to create/handle/destroy such buffers? (using libdrm if I got it correctly). Is there an example somewhere?</p>\n",
    Owner: "users/151276",
    LastEditor: null,
    LastEditDate: null,
    Title: "How to fetch images from camera with DMA?",
    Tags: ["camera"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180298-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/145112",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1724401Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-11-20T21:48:12.2970000",
    Score: 0,
    ViewCount: 29,
    Body: "<p>When I type the command &quot;vcgencmd get_camera,&quot; I get the following output: supported=0 detected=0, libcamera interfaces=0</p>\n<p>And when I type the command &quot;libcamera-still -o test.jpg,&quot; I get the image generated from the camera. How is this possible?</p>\n",
    Owner: "users/157970",
    LastEditor: null,
    LastEditDate: null,
    Title: "Pi Camera V2 not working",
    Tags: ["raspbian", "camera", "raspicam", "picamera"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180254-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/145032",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1658977Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-11-19T17:22:39.4630000",
    Score: 0,
    ViewCount: 12,
    Body: "<p>libcamera-hello: how to know the actual device used?</p>\n<p>The <code>--list-camera</code> option gives:</p>\n<pre><code>$ libcamera-hello --list-camera\nAvailable cameras\n-----------------\n0 : imxXYZ [wxh] (/base/soc/i2c0mux/i2c@1/imxXYZ@1a)\n</code></pre>\n<p>So you can select he camera with <code>--camera</code>:</p>\n<pre><code>$ libcamera-hello --camera 0\n</code></pre>\n<p>... But how to know the <code>/dev/video*</code> associated to <code>--camera 0</code>?</p>\n<p>Ideally, is there a way to get the same result than <code>libcamera-hello</code> but with <code>v4l2-ctl</code> (specifying all options at command line)?</p>\n",
    Owner: "users/151276",
    LastEditor: null,
    LastEditDate: null,
    Title: "libcamera-hello: how to know the actual device used?",
    Tags: ["camera", "libcamera"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180247-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/145019",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1651253Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-11-16T17:24:21.4700000",
    Score: 0,
    ViewCount: 45,
    Body: "<p>I have a Raspberry Pi 4. No camera (nor CSI, nor USB) is plugged.</p>\n<p>The Pi comes basically out of the box: installed a fresh raspbian with default <code>/boot/config.txt</code>. I just added an overlay for a (CSI) camera that is <strong>not</strong> yet plugged.</p>\n<p>My blurry understanding at that point is that all video-related stuffs are associated to devices such like video, hidraw and/or media.</p>\n<p>I turn the raspberry on <strong>without</strong> any camera plugged and was surprised to find so many devices:</p>\n<pre><code>~ $ libcamera-hello --list-cameras\nNo cameras available!\n\n~ $ ls -al /dev/video*\ncrw-rw----+ 1 root video 81,  4 Nov 15 23:05 /dev/video10\ncrw-rw----+ 1 root video 81,  5 Nov 15 23:05 /dev/video11\ncrw-rw----+ 1 root video 81,  7 Nov 15 23:05 /dev/video12\ncrw-rw----+ 1 root video 81,  0 Nov 15 23:05 /dev/video13\ncrw-rw----+ 1 root video 81,  1 Nov 15 23:05 /dev/video14\ncrw-rw----+ 1 root video 81,  2 Nov 15 23:05 /dev/video15\ncrw-rw----+ 1 root video 81,  3 Nov 15 23:05 /dev/video16\ncrw-rw----+ 1 root video 81,  9 Nov 15 23:05 /dev/video18\ncrw-rw----+ 1 root video 81, 12 Nov 15 23:05 /dev/video19\ncrw-rw----+ 1 root video 81,  6 Nov 15 23:05 /dev/video20\ncrw-rw----+ 1 root video 81,  8 Nov 15 23:05 /dev/video21\ncrw-rw----+ 1 root video 81, 10 Nov 15 23:05 /dev/video22\ncrw-rw----+ 1 root video 81, 11 Nov 15 23:05 /dev/video23\ncrw-rw----+ 1 root video 81, 13 Nov 15 23:05 /dev/video31\n\n~ $ ls -al /dev/media*\ncrw-rw---- 1 root video 238, 0 Nov 15 23:05 /dev/media0\ncrw-rw---- 1 root video 238, 1 Nov 15 23:05 /dev/media1\ncrw-rw---- 1 root video 238, 2 Nov 15 23:05 /dev/media2\ncrw-rw---- 1 root video 238, 3 Nov 15 23:05 /dev/media3\ncrw-rw---- 1 root video 238, 4 Nov 15 23:05 /dev/media4\n\n~ $ ls -al /dev/hidraw*\ncrw------- 1 root root 241, 0 Nov 15 23:05 /dev/hidraw0\ncrw------- 1 root root 241, 1 Nov 15 23:05 /dev/hidraw1\ncrw------- 1 root root 241, 2 Nov 15 23:05 /dev/hidraw2\ncrw------- 1 root root 241, 3 Nov 15 23:05 /dev/hidraw3\n\n</code></pre>\n<p>Question 1: why is there so many devices by default? What are they supposed to be used for and how? Example: for what purpose can I use <code>/dev/video10</code>, <code>/dev/media0</code> or <code>/dev/hidraw0</code> if no camera is plugged?!...</p>\n<p>Question 2: can somebody shed some light, roughly speaking, on the different types of devices (video, media, hidraw)? What each type is made for?</p>\n",
    Owner: "users/151276",
    LastEditor: null,
    LastEditDate: null,
    Title: "Raspberry Pi 4: available devices?",
    Tags: ["camera"],
    FavoriteCount: 0,
    Answers: [
      {
        Id: 144998,
        CreationDate: "2023-11-16T18:08:57.1770000",
        Score: 0,
        ViewCount: 0,
        Body: "<p>These devices are initialized by default in the anticipation that you might connect corresponding hardware in the future. When you do connect devices, the system will use these nodes to interact with the connected hardware. Until then, they serve as placeholders for potential devices.</p>\n",
        Owner: "users/154605",
        LastEditor: null,
        LastEditDate: null,
        Comments: [],
      },
      {
        Id: 145002,
        CreationDate: "2023-11-17T10:46:44.6370000",
        Score: 0,
        ViewCount: 0,
        Body: "<p>These are character devices (as indicated by the leading 'c' on the listing).</p>\n<p>They do not indicate physical devices but are a link to the device driver in the kernel.</p>\n<p>There are a gazillion of them in <code>/dev</code> (the others which are not character devices are block devices indicated by a leading 'b').</p>\n<p>In general user programs can send a character to them and/or receive a character in response depending on the device. A common example of a bidirectional device is <code>/dev/i2c-1</code>. This is loaded by the <code>dtparam=i2c_arm=on</code> entry in <code>config.txt</code>.</p>\n<p>The listing of an entry indicates a device driver is active which may or may not have a physical device attached.</p>\n<p>E.g <code>i2cdetect 1</code> on one of my Pi indicates 3 devices at addresses 20, 57, 68 but on other Pi there are no corresponding physical devices attached although both have <code>/dev/i2c-1</code></p>\n",
        Owner: "users/8697",
        LastEditor: "users/8697",
        LastEditDate: "2023-11-17T11:30:07.6000000",
        Comments: [],
      },
    ],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180233-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/144997",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1632560Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-11-05T06:32:05.1530000",
    Score: 0,
    ViewCount: 59,
    Body: "<p>I have a problem with my Arducam OV5647 M32076M20. It simply will not work unlike the other generic rpi camera I have on the same code. I am unsure if there are any other dependencies that I need for this.</p>\n<p>Things to note:</p>\n<ul>\n<li><p><code>vcgencmd get_camera</code> returns <code>supported=1 detected=1, libcamera interfaces=0</code></p>\n</li>\n<li><p>I am using <code>OpenCV</code> and <code>tkinter</code> and its basically just a simple program that shows what the camera sees when its turned on. It works on other camera except the one I've shown</p>\n</li>\n<li><p>I have a script that detects camera with cv2 and it returns positive with <code>video0</code> usually</p>\n<pre><code> for i in range(10):\n     vid = cv2.VideoCapture(i)\n     if vid.isOpened():\n         status_label.config(text=&quot;Camera Found\\tPort: video&quot; + str(i), fg=&quot;green&quot;)\n         print(&quot;Camera Found port: &quot; + str(i))\n         break\n</code></pre>\n</li>\n<li><p>GPU Memory is at <code>256</code></p>\n</li>\n<li><p><code>libcamera-hello</code> runs and I see myself in the camera but I cannot get it to work in the software I coded</p>\n</li>\n<li><p>Legacy Camera is <code>enabled</code> in <code>raspi-config</code></p>\n</li>\n<li><p>Details of <code>cat /etc/os-release</code></p>\n<pre><code> PRETTY_NAME=&quot;Raspbian GNU/Linux 11 (bullseye)&quot;\n NAME=&quot;Raspbian GNU/Linux&quot;\n VERSION_ID=&quot;11&quot;\n VERSION=&quot;11 (bullseye)&quot;\n VERSION_CODENAME=bullseye\n ID=raspbian\n ID_LIKE=debian\n</code></pre>\n</li>\n</ul>\n<p>Really stumped at this. does Arducam have specific dependencies that I somehow missed. -I am just hoping that theres no need to buy the same module again to compare- <strong>Edit: Nope. Even with another module its still the same</strong></p>\n<p>Edit:\nI tried <code>dmesg</code> and saw these</p>\n<pre><code>    [ 1638.317199] unicam fe801000.csi: Failed to start media pipeline: -22\n    [ 1678.153954] unicam fe801000.csi: Wrong width or height 640x480 (remote pad set to 1296x972)\n</code></pre>\n<p>I am still trying to figure out what this means</p>\n<p>I get <code>global cap_v4l.cpp: 1119 tryIoctl VIDEOI0(V4L2:/dev/video0): select() timeout</code> now that i did a fresh install and everything.</p>\n",
    Owner: "users/157677",
    LastEditor: "users/157677",
    LastEditDate: "2023-11-09T03:59:45.9600000",
    Title: "Arducam Refusing to Connect but other Camera works with OpenCV",
    Tags: ["camera", "opencv", "raspberry-pi-os-bullseye-64"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180174-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/144874",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:48.1546557Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-10-18T16:37:28.4700000",
    Score: 0,
    ViewCount: 21,
    Body: "<p>I have a Python program that utilizes threading to run multiple processes on a single webcam. The code works perfectly fine on my laptop, where it can run different processes simultaneously on one camera. However, when I try to run the same code on my Raspberry Pi 4, it does not work at all... I don't understand why it's not working.</p>\n<pre><code>import threading\nfrom Head import HeadTracking\nfrom Hand2 import HandTracking\nfrom Monitoring import video_stream\n\nif __name__ == '__main__':\n    head_tracking = HeadTracking()\n    hand_tracking = HandTracking()\n    video_stream = video_stream\n\n    head_thread = threading.Thread(target=head_tracking.run)\n    hand_thread = threading.Thread(target=hand_tracking.run)\n    video_thread = threading.Thread(target=video_stream)\n\n    head_thread.start()\n    hand_thread.start()\n    video_thread.start()\n\n    head_thread.join()\n    hand_thread.join()\n    video_thread.join()\n</code></pre>\n",
    Owner: "users/157414",
    LastEditor: null,
    LastEditDate: null,
    Title:
      "Issue with running multiple processes on a single webcam with Raspberry Pi 4",
    Tags: ["raspbian", "python", "pi-4", "camera", "real-time"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180086-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/144698",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:47.9600645Z",
    },
  },
  {
    AcceptedAnswerId: 0,
    Community: "raspberrypi",
    CreationDate: "2023-10-12T03:29:29.5200000",
    Score: 0,
    ViewCount: 18,
    Body: "<p>I encounter issues when reading from 2 cameras simultaneously in Raspberry Pi 4.</p>\n<p>I connected an RGB camera to the USB3.0 port and another B/W camera to USB2.0 since cameras would be disconnected when I connected them to the same USB3.0 port.</p>\n<p>I notice that some camera frames arrive corrupted if I run both cameras only. I thought usb2.0 and usb3.0 USB roots would be independent. Is there any way to verify if I am hitting any capacity with the USB bus, CPU-read, or any other resources?</p>\n",
    Owner: "users/157299",
    LastEditor: null,
    LastEditDate: null,
    Title: "Understanding USB in Raspberry Pi Model 4",
    Tags: ["pi-4", "usb", "camera", "usb3"],
    FavoriteCount: 0,
    Answers: [],
    Comments: [],
    "@metadata": {
      "@collection": "Questions",
      "Raven-Clr-Type": "Question, StackExchange.Import",
      "@change-vector": "A:180059-PMuQEi92dkClK2hwMQItUw",
      "@id": "questions/144634",
      "@index-score": 4.559910774230957,
      "@last-modified": "2024-01-22T17:15:47.9564949Z",
    },
  },
];

export async function getQuestions() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(demoQuestions);
    }, 2000);
  });
}

const demoQuesiton = {
  Community: "raspberrypi",
  AcceptedAnswerId: 0,
  CreationDate: "2023-06-21T00:26:45.3300000",
  Score: 0,
  ViewCount: 748,
  Body: "<p>I am new to Raspberry Pi and I want to do real-time object detection using YOLOv8 tentatively (will change if the fps is too low). I realize that by using the code below, it can't detect Pi Cam as the source and run into an error. The Pi Cam works fine with <code>libcamera-hello</code> and managed to capture photo everything. I also enabled the legacy camera feature. The code works fine with USB webcam.</p>\n<p>Code:</p>\n<pre><code>from ultralytics import YOLO\n\nmodel = YOLO('best.pt')\nresults = model.predict(source=0, show=True)\n\nprint(results)\n</code></pre>\n<p>Error:\nConnectionError: 1/1: 0... Failed to read images from 0</p>\n<p>I thought of one solution which is to capture image every time and pass to the model to predict, but it only produces an image every 2.5s. I guess maybe the model reinitialize every time it predicts an image again.</p>\n<p>Code:</p>\n<pre><code>import cv2\nfrom picamera2 import Picamera2\nfrom ultralytics import YOLO\nimport numpy as np\n\ncv2.startWindowThread()\n\npicam2 = Picamera2()\npicam2.configure(picam2.create_preview_configuration(main={&quot;format&quot;: 'XRGB8888', &quot;size&quot;: (640, 480)}))\npicam2.start()\n\nmodel = YOLO('best.pt')\n\nwhile True:\n    im = picam2.capture_array()\n\n    img = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)\n    results = model.predict(img)\n\n    for box in results[0].boxes:\n        x = int(np.floor(box[0].xywh[0][0].item()))\n        y = int(np.floor(box[0].xywh[0][1].item()))\n        w = int(np.floor(box[0].xywh[0][2].item()))\n        h = int(np.floor(box[0].xywh[0][3].item()))\n        \n        cv2.rectangle(im, (x, y), (x + w, y + h), (0, 255, 0))\n\n    cv2.imshow(&quot;Camera&quot;, im)\n</code></pre>\n<p>So, there are two questions in my mind:</p>\n<ol>\n<li>How to set Pi Cam as the default <code>source=0</code> to have real-time object detection using YOLOv8?</li>\n<li>How to prevent reinitialization of the YOLO model for image prediction? (If my guess is correct)</li>\n</ol>\n",
  Owner: "users/raspberrypi/155333",
  LastEditor: null,
  LastEditDate: null,
  Title: "How to stream from Pi Camera to YOLO model?",
  Tags: ["camera", "webcam", "picamera", "streaming"],
  FavoriteCount: 0,
  Answers: [
    {
      Id: 143637,
      CreationDate: "2023-07-05T01:54:00.9270000",
      Score: 0,
      ViewCount: 0,
      Body: "<p>I got an idea:</p>\n<ol>\n<li><p>to see if the Pi Cam can be detected by your computer<br />\nin cmd:\n'pip install pygame'<br />\nand run the following python code<br />\n<code>import pygame.camera</code><br />\n<code>pygame.camera.init()</code><br />\n<code>camera_id_list = pygame.camera.list_cameras()</code><br />\n<code>print(camera_id_list)</code><br />\nIf the result comes out to be 0 which is the id of your computer own cam, you can't use the Pi cam directly.If there are other numbers in the result,  you can try by changing to 'source=1' for example.</p>\n</li>\n<li><p>to get other components provided by raspberrypi<br />\nI don't have an intimate knowledge of this, so I can't offer you some valuable suggestions.</p>\n</li>\n<li><p>to read the picamera document<br />\nclick the link: <a href=\"https://picamera.readthedocs.io/en/release-1.13/recipes2.html\" rel=\"nofollow noreferrer\">https://picamera.readthedocs.io/en/release-1.13/recipes2.html</a><br />\nand you can see something helpful for you in the section <code>4.2 Capturing to an OpenCV object</code></p>\n</li>\n</ol>\n",
      Owner: "users/raspberrypi/155566",
      LastEditor: "users/raspberrypi/155566",
      LastEditDate: "2023-07-05T03:20:38.4070000",
      Comments: [],
    },
    {
      Id: 145169,
      CreationDate: "2023-12-02T13:52:18.2100000",
      Score: 0,
      ViewCount: 0,
      Body: '<p>Check out the Ultralytics docs on this: <a href="https://docs.ultralytics.com/guides/raspberry-pi/#quick-start-with-yolov8" rel="nofollow noreferrer">https://docs.ultralytics.com/guides/raspberry-pi/#quick-start-with-yolov8</a></p>\n',
      Owner: "users/raspberrypi/157763",
      LastEditor: null,
      LastEditDate: null,
      Comments: [
        {
          Id: 248153,
          Score: 0,
          Text: "While this link may answer the question, it is better to include the essential parts of the answer here and provide the link for reference.  Link-only answers can become invalid if the linked page changes. - [From Review](/review/late-answers/133023)",
          CreationDate: "2023-12-03T01:07:08.5900000",
          User: "users/raspberrypi/8697",
        },
      ],
    },
  ],
  Comments: [
    {
      Id: 248153,
      Score: 0,
      Text: "While this link may answer the question, it is better to include the essential parts of the answer here and provide the link for reference.  Link-only answers can become invalid if the linked page changes. - [From Review](/review/late-answers/133023)",
      CreationDate: "2023-12-03T01:07:08.5900000",
      User: "users/raspberrypi/8697",
    },
  ],
  "@metadata": {
    "@collection": "Questions",
    "Raven-Clr-Type": "Question, StackExchange.Import",
  },
};

export async function getQuestion() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(demoQuesiton);
    }, 2000);
  });
}
