<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="RavenDB.Client" Version="7.2.5" />
    <PackageReference Include="SharpCompress" Version="0.49.1" />
    <Compile Include="../ImportStackExchangeDump.cs" Link="Program.cs" />
  </ItemGroup>
</Project>
